---
abstract: "[One line description of module's purpose here]"
author:
  - 'Atsushi NAGASE  C<< <ngs@cpan.org> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Android-Drawable
no_index:
  directory:
    - inc
    - t
requires:
  XML::TreePP: 0
resources:
  homepage: http://github.com/ngs/p5-android-drawable/tree
  license: http://dev.perl.org/licenses/
  repository: git://github.com/ngs/p5-android-drawable.git
version: 0.000003
